// <auto-generated />
using System;
using FHLProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FHLProject.Migrations
{
    [DbContext(typeof(CDsDBContext))]
    partial class CDsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FHLProject.Models.CDs", b =>
                {
                    b.Property<int>("cdID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CD_Number");

                    b.Property<string>("CD_Place");

                    b.Property<string>("CD_Surname");

                    b.Property<string>("CD_Titles");

                    b.Property<int>("Concurrent");

                    b.Property<string>("Location");

                    b.Property<int>("QS_Number");

                    b.Property<int>("Title_Number");

                    b.Property<DateTime>("Update_Date");

                    b.HasKey("cdID");

                    b.ToTable("CDs");
                });
#pragma warning restore 612, 618
        }
    }
}
